apiVersion: v1
entries:
  rustic:
  - apiVersion: v2
    appVersion: 0.7.0
    created: "2024-02-18T10:55:53.386175116+01:00"
    description: fast, encrypted and deduplicated backups
    digest: 2bc1f8ffb051210a595a7cd8097d35f77e378a3d5b4d82eafc7fbc9cc883f11f
    name: rustic
    type: application
    urls:
    - https://github.com/rustic-rs/rustic-helm/releases/download/0.2.0-alpha/rustic-0.2.0-alpha.tgz
    version: 0.2.0-alpha
  - apiVersion: v2
    appVersion: 0.6.1
    created: "2024-01-12T18:11:53.714144944+01:00"
    description: fast, encrypted and deduplicated backups
    digest: dac3ca6875a462a0fd77bbc3300d743e260f23ca7e6a7cd1949fea1b51b44c16
    name: rustic
    type: application
    urls:
    - https://github.com/rustic-rs/rustic-helm/releases/download/0.1.1-alpha/rustic-0.1.1-alpha.tgz
    version: 0.1.1-alpha
  - apiVersion: v2
    appVersion: 0.6.1
    created: "2024-01-06T14:01:32.369624462+01:00"
    description: fast, encrypted and deduplicated backups
    digest: 8e783811d5bcd0adfd3778af753e9839aaedf2a3dd529124f3285a25f896cf95
    name: rustic
    type: application
    urls:
    - https://github.com/rustic-rs/rustic-helm/releases/download/0.1.0-alpha/rustic-0.1.0-alpha.tgz
    version: 0.1.0-alpha
generated: "2024-02-18T10:55:53.383180364+01:00"
